[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget gnupg ca-certificates",
    "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list'",
    "apt-get update",
    "apt-get install -y google-chrome-stable",
]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = [
    "npx puppeteer browsers install chrome",
    "chmod -R o+rx node_modules/puppeteer/.local-chromium"
]

[start]
cmd = "node server.js"
